### ISSUE TITLE
Update Configs for OTLP Tracking

### ISSUE THREAD

**Issue by renaz6** [xmidt-org/candlelight#85]
Tracking work to be done to get OTLP/tracing up and running.

Xmidt/WebPA
- [x] Tr1d1um https://github.com/xmidt-org/tr1d1um/pull/346
- [x] Scytale https://github.com/xmidt-org/scytale/pull/220
- [x] Argus https://github.com/xmidt-org/argus/pull/371
- [x] Themis https://github.com/xmidt-org/themis/pull/137
- [x] Petasos https://github.com/xmidt-org/petasos/pull/123
- [x] Talaria https://github.com/xmidt-org/talaria/pull/282
- [x] Caduceus https://github.com/xmidt-org/caduceus/pull/372

Nion

- [x] Reeve 
- [x] Scrivener
- [ ] Ewerer
- [x] Fletcher
